pipeline:
  test:
    image: python:3.6
    commands:
      - cd code
      - pip install -r requirements.txt
      - python ./test_database.py
  backend:
    image: plugins/docker
    repo: nielsole/ycombinator_newsletter
    username: ${DRONE_USERNAME}
    password: ${DRONE_PASSWORD}
    tags:
      - latest